### ISSUE TITLE
Bug WaitForWorkers

### ISSUE THREAD

**Issue by ludovicc** [LREN-CHUV/woken#5]
After running an experiment from the Web portal, Woken seems to fall into an incorrect state and refuses to handle further requests. 

[WARN] [06/26/2017 13:38:37.090] [woken-akka.actor.default-dispatcher-19] [akka.tcp://woken@hosxxxx.intranet.chuv:4090/user/$g] unhandled event Start(Job(89d6a676-db22-4c2e-a568-a8f4fea0a034,Some(ldsm),List(Algorithm(linearRegression,Linear Regression,Map()), Algorithm(knn,K-nearest neighbors with k=5,Map(k -> 5))),List(Validation(kfold,Untitled validation,Map(k -> 2))),Map(PARAM_variables -> subjectageyears, PARAM_query -> select subjectageyears,leftventraldc,rightventraldc from merged_data where subjectageyears is not null and leftventraldc is not null and rightventraldc is not null, PARAM_grouping -> , PARAM_meta -> {"subjectageyears":{"description":"Subject age in years.","methodology":"mip-cde","label":"Age Years","minValue":0,"code":"subjectageyears","units":"years","length":3,"maxValue":130,"type":"integer"},"leftventraldc":{"description":"","methodology":"lren-nmm-volumes","label":"Left Ventral DC","code":"leftventraldc","units":"cm3","length":20,"type":"real"},"rightventraldc":{"description":"","methodology":"lren-nmm-volumes","label":"Right Ventral DC","code":"rightventraldc","units":"cm3","length":20,"type":"real"}}, PARAM_covariables -> leftventraldc,rightventraldc))) in state WaitForWorkers

**Comment by devsprint** [comment]
https://github.com/LREN-CHUV/woken/pull/6 - fix for this issue.

**Comment by ludovicc** [comment]
Fixed indeed. I added more checks to detect and cleanup bad jobs on Chronos
